### PR TITLE
Fullscreen fix

### LINKED ISSUE #1460: Expended View missing ui elements.
**Description:**
When expending the query view to see the graph, 
The ability to change colors, size, and all the other properties, disappear.

**Expectation:**
Able to change properties from an expanded view.

Attaching Screenshots below.

Screen Shot 2021-07-05 at 15 45 37

Screen Shot 2021-07-05 at 15 46 43

### PR DESCRIPTION
**Pull request by OskarDamkjaer**
To solve the problem of the bottom bar moving of the screen when adding lines to a query in fullscreen a new flexbox was added to give the middle content 100% height and scroll on overflow, taking the available space not used for the editor or the bottom bar. For the main viz though, resizing the container seems to change the size of the nodes, so I've opted to use position fixed for the bottom bar and zoom controls there. Worth noting that the viz bottom bar is probably going away soon as part of our work on node properties. I'm sure there's a cleaner way to structure the css and element tree, so far this is the cleanest I've worked out after too many hours of fiddling. 

preview @ http://fullscreen_fix.surge.sh

Fixes #1460 
image

### CODE REVIEW

File: src/browser/modules/D3Visualization/components/Explorer.tsx [hunk 1]
```diff
@@ -205,10 +205,6 @@ export class ExplorerComponent extends Component<any, ExplorerComponentState> {
         />
       )
     }
-    const inspectingItemType =
```
Comment (OskarDamkjaer) [inline src/browser/modules/D3Visualization/components/Explorer.tsx:208]: unused

File: src/browser/modules/D3Visualization/components/styled.tsx [hunk 2]
```diff
@@ -181,12 +181,13 @@ export const StyledStatusBarWrapper = styled.div`
   display: none;
 `
 
-export const StyledStatusBar = styled.div`
+export const StyledStatusBar = styled.div<{ fullscreen?: boolean }>`
```
Comment (OskarDamkjaer) [inline src/browser/modules/D3Visualization/components/styled.tsx:184]: This is the status bar used for in the cypher frame

File: src/browser/modules/D3Visualization/components/styled.tsx [hunk 3]
```diff
@@ -337,8 +338,8 @@ export const StyledInspectorFooterStatusMessage = styled.div`
   font-weight: bold;
 `
 
-export const StyledZoomHolder = styled.div`
-  position: absolute;
+export const StyledZoomHolder = styled.div<{ fullscreen: boolean }>`
+  position: ${props => (props.fullscreen ? 'fixed' : 'absolute')};
```
Comment (OskarDamkjaer) [inline src/browser/modules/D3Visualization/components/styled.tsx:342]: The zoombuttons on the cypherframe

File: src/browser/modules/Frame/styled.tsx [hunk 4]
```diff
@@ -122,8 +123,16 @@ export const StyledFrameContents = styled.div<FullscreenProps>`
 
 export const StyledFrameStatusbar = styled.div<FullscreenProps>`
```
Comment (OskarDamkjaer) [inline src/browser/modules/Frame/styled.tsx:124]: This is the bottom panel used in CypherFrame, when we're **not** showing a graph visualization

File: src/browser/modules/D3Visualization/components/styled.tsx [hunk 5]
```diff
@@ -181,12 +181,13 @@ export const StyledStatusBarWrapper = styled.div`
...
 
-export const StyledStatusBar = styled.div`
+export const StyledStatusBar = styled.div<{ fullscreen?: boolean }>`
   min-height: 39px;
   line-height: 39px;
   color: ${props => props.theme.secondaryText};
   font-size: 13px;
-  position: absolute;
+  position: ${props => (props.fullscreen ? 'fixed' : 'absolute')};
+  z-index: ${props => (props.fullscreen ? 1 : 0)};
```
Comment (jharris4) [inline src/browser/modules/D3Visualization/components/styled.tsx:190]: the default for z-index is `auto`, so we should use `unset` or `auto` instead of `0` here (and elsewhere when the intention is to have it perform as it was before)

File: src/browser/modules/Frame/styled.tsx [hunk 6]
```diff
@@ -123,7 +124,6 @@ export const StyledFrameContents = styled.div<FullscreenProps>`
...
   border-top: ${props => props.theme.inFrameBorder};
   height: ${dim.frameStatusbarHeight - 1}px;
-  ${props => (props.fullscreen ? 'margin-top: -78px;' : '')};
```
Comment (jharris4) [inline src/browser/modules/Frame/styled.tsx:126]: NICE if we can get rid of this :-D

**Comment by jharris4** [comment]
These changes look good so far, but let's wait for the node properties panel work to progress further before merging this. (cc @jk05 )

**Review by jharris4 — APPROVED** [review]
I noticed a small issue with the position of the expand toggle button (triangle in bottom right) when the status bar is multi-line, but it's not a big deal, and will get replaced anyway once we finish the node properties feature.
