### PR TITLE
Only remove :auto if it is a prefix

### LINKED ISSUE #1149: Query not returning expected data after upgrade from 3.5.16 community to 3.5.19 enterprise
Hi there, I observed some unexpected query behaviors. Please see this [forum thread](https://community.neo4j.com/t/really-weird-query-not-returning-expected-data-after-upgrade-from-3-5-16-community-to-3-5-19-enterprise/21672) for full context.

> Neo4j version

3.5.19 Enterprise

> Operating system: (for example Windows 95/Ubuntu 16.04)

Ubuntu 14.04.6 LTS

> API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)

The script that fills my DB uses 1.7.6 of the Python driver

## Description

I recently upgraded my DB from 3.5.16 community to 3.5.19 with the following procedure:

1. `service stop neo4j`
1. Uninstall Neo4j Community 3.5.16, keeping the old data
1. `apt-get install neo4j-enterprise=3.5.19`
1. `service start neo4j`

This query works as expected: 
```
match (n:AWSTag) 
where n.key contains "aws:auto" 
return n.key, n.value 
order by n.key limit 300
``` 
as it returns a list of nodes with n.key = aws:autoscaling:groupName:

image

However when I just add an "s" to the key filter by running 
```
match (n:AWSTag)
where n.key contains "aws:autos"
return n.key, n.value
order by n.key limit 300
```
I get 0 results:

image

I have a second neo4j server that was also upgraded using the same steps, running similar data and it shows this exact problem as well.

Things I've tried:

- I have tried deleting all indexes on this :AWSTag node but that didn't work.
- I then tried turning off the server, deleting /var/lib/neo4j/data/databases/graph.db/schema/*, and turning it on again.
All other queries except for those related to `:AWSTags` work as expected (I think).

- PROFILE of the successful query:
    image

- PROFILE of the failing query: 
    image

Here are some other observations.

### Expected behavior

```
match (n:AWSTag) 
where n.key contains "aws:autos" 
return n.key, n.value 
order by n.key limit 300
```
should return a table that looks like

|n.key|n.value|
|-|-|
| aws:autoscaling:groupName | some group name | 
| aws:autoscaling:groupName | some other group name | 

### Actual behavior
The above query returns zero results.

### Expected

```
match (a:AWSTag)
where a.key starts with "aws:auto"
return distinct a.key
```
should return only keys that actually start with "aws:auto".

### Actual

The above query has these results:

image

### Expected
If I do an exact field search like 
```
match (a:AWSTag{key:"aws:autoscaling:groupName"}) return a
```

I should get back nodes with `key='aws:autoscaling:groupName`, as shown in the "Description" above.

### Actual 

I get no results.
image

## Additional information

- Partial output of `CALL db.stats.retrieve("GRAPH COUNTS")`

    ```json
    {
      "relationships": [
        {
          "count": 8882403
        },

        {
          "relationshipType": "TAGGED",
          "count": 97277,
          "endLabel": "AWSTag"
        },
        {
          "relationshipType": "TAGGED",
          "count": 97277,
          "endLabel": "Tag"
        },

      ],
      "nodes": [
        {
          "count": 2855520
        },

        {
          "count": 66181,
          "label": "AWSTag"
        },
        {
          "count": 66181,
          "label": "Tag"
        },

      ],
      "indexes": [

        {
          "updatesSinceEstimation": 2134,
          "totalSize": 64047,
          "properties": [
            "id"
          ],
          "labels": [
            "AWSTag"
          ],
          "estimatedUniqueSize": 64047
        },

      ],
      "constraints": []
    }
    ```

### PR DESCRIPTION
**Pull request by OskarDamkjaer**
Previously ":auto" would be removed from the middle of queries such as "match (n) where n.key = "test:auto". 

Resolves #1149

### CODE REVIEW

**Review by HerrEmil — APPROVED** [review]

File: src/shared/services/commandInterpreterHelper.js [hunk 1]
```diff
@@ -384,18 +384,17 @@ const availableCommands = [
...
-      // Since we now also handle queries with the :auto prefix, we need to strip that
-      // and attach to the actions object
-      const query = action.cmd.replace(
-        getCmdChar(state) + autoCommitTxCommand,
-        ''
-      )
-      action.query = query.trim()
+      // Since we now also handle queries with the :auto prefix,
+      // we need to strip that and attach to the actions object
+      const query = action.cmd.trim()
```
Comment (oskarhane) [inline src/shared/services/commandInterpreterHelper.js:389]: This should strip any comments as well.

```
// Comment
:auto CREATE (n:Test {val: 'yo:auto'}) RETURN *
```
will now fail

Comment (OskarDamkjaer) [reply src/shared/services/commandInterpreterHelper.js:389]: Good catch!

Comment (OskarDamkjaer) [reply src/shared/services/commandInterpreterHelper.js:392]: I updated the implementation and added some tests

File: src/shared/services/commandInterpreterHelper.js [hunk 2]
```diff
@@ -384,18 +384,22 @@ const availableCommands = [
...
+        .replace(/\/\/[^\n]*\n/g, '') // singleline comment
+        .trim()
+        .startsWith(autoPrefix)
 
-      // We need to find out if this is an auto-committing tx or not
-      // i.e. Did we strip something off above here?
-      const autoCommit = action.query.length < action.cmd.trim().length
-      action.autoCommit = autoCommit
+      action.autoCommit = isAutocommit
+      action.query = isAutocommit ? query.replace(autoPrefix, '').trim() : query
```
Comment (HerrEmil) [inline src/shared/services/commandInterpreterHelper.js:402]: I think replacing first instance of a text will fail if a comment has the text being replaced, e.g.
```
// browser should remove :auto in the query below this comment
:auto CREATE (n:Test {val: 'yo:auto'}) RETURN *
```

File: src/browser/modules/Stream/CypherFrame/VisualizationView.jsx [hunk 3]
```diff
@@ -93,6 +93,7 @@ export class Visualization extends Component {
 
       this.getInternalRelationships(existingNodeIds, newNodeIds)
         .then(graph => {
+          console.log(graph.relationships)
```
Comment (HerrEmil) [inline src/browser/modules/Stream/CypherFrame/VisualizationView.jsx:96]: Leftover console.log

Comment (OskarDamkjaer) [reply src/browser/modules/Stream/CypherFrame/VisualizationView.jsx:96]: Thanks! It was for an unrelated change

File: src/shared/services/commandInterpreterHelper.js (hunk 2 above)
Comment (OskarDamkjaer) [reply src/shared/services/commandInterpreterHelper.js:402]: Right. Thinking of how this is best solved without a proper parse.. I'll send an update, do tell what you think

Comment (OskarDamkjaer) [reply src/shared/services/commandInterpreterHelper.js:402]: Hmm... none of these handle the case of `:auto return 1; :auto return 1;`. Is that statement legal with multiline enabled?

Comment (OskarDamkjaer) [reply src/shared/services/commandInterpreterHelper.js:402]: Not sure what the best way forward (barring a proper parse) is. This query for example bypasses the easy-ish solutions I can think of.. `/* :auto */ :auto RETURN 1;`

Comment (HerrEmil) [reply src/shared/services/commandInterpreterHelper.js:402]: The issue I noted is already an issue in production, this fix does not cause any extra issue

**Review by HerrEmil — APPROVED** [review]
